### ISSUE TITLE
A Better Docker Development Workflow - node lts image issue

### ISSUE THREAD

**Issue by eliassal** [craigbuckler/docker-demo#3]
Hi Craig, I am reading your post at https://www.sitepoint.com/node-js-docker/ , I tried your code

docker run --rm --name version \
 ```
 -v $PWD:/home/node/app \
  -w /home/node/app \
  node:lts-alpine version.js
```

1st, not sure where I should be in order for the details in -v flag should be correct. I created inside my home a the following structure
node/app so 
`$PWD/node/app`
resolves to
`/home/salam/Projects/node-js-docker/node/app`
where version.js is located
However running the command errors as follows

```
docker run --rm --name version   -v $PWD:/node/app   -w /home/node/app   node:lts-alpine node version.js
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module '/home/node/app/version.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.10.0
```

What is wrong here, please?

**Comment by craigbuckler** [comment]
Hi,

Execute the "docker run" command from the directory where version.js is located.

All files in that directory are mapped to /home/node/app inside the Docker container.

What OS are you using? Check that $PWD resolves to the current directory.

I hope that helps.
Craig
________________________________
From: eliassal ***@***.***>
Sent: 02 January 2024 17:31
To: craigbuckler/docker-demo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [craigbuckler/docker-demo] A Better Docker Development Workflow - node lts image issue (Issue #3)


Hi Craig, I am reading your post at https://www.sitepoint.com/node-js-docker/ , I tried your code

docker run --rm --name version \

-v $PWD:/home/node/app \
 -w /home/node/app \
 node:lts-alpine version.js


1st, not sure where I should be in order for the details in -v flag should be correct. I created inside my home a the following structure
node/app so
$PWD/node/app
resolves to
/home/salam/Projects/node-js-docker/node/app
where version.js is located
However running the command errors as follows

docker run --rm --name version   -v $PWD:/node/app   -w /home/node/app   node:lts-alpine node version.js
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module '/home/node/app/version.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.10.0


What is wrong here, please?

**Comment by eliassal** [comment]
So many thanks Craig, I diont why, today, it is working and I was able to follow up to the "Debug with VS Code" where I got stuck.
I create the launch.json as per your code, attch to debugger and I can see it is attached to debugger but in VS code, the breakpoint indicates "Breakpoint set but not yet bound" so when I refresh index.js nothing happens

![image](https://github.com/craigbuckler/docker-demo/assets/8447864/d2f78ab6-fafc-431b-8c93-60ee7fc53af4)

![image](https://github.com/craigbuckler/docker-demo/assets/8447864/2f1bc214-17ed-4235-ac7a-0c8aee019f19)

**Comment by craigbuckler** [comment]
Hi,

It sounds like the debugger's attaching, but it can't map/associate your local file to the one running in the Docker container. Double-check your launch.json file. It's possible something's changed in VS Code recently or you're using an older installation, but that seems unlikely. Check all the steps carefully.

I hope that helps.
Craig
________________________________

**Comment by eliassal** [comment]
Yes Craig, It is the VS Code version on Ubuntu. I ran the whole exercise on a win 10 box, it worked like a charm and I was able to debug and step into the code as expected. So many thanks for your efforts and help.
One question though, have you tried to do the same thing when the container runs inside Kubernetes Pod? Is it the same thing or it is different?

**Comment by craigbuckler** [comment]
Hi,

VS Code on Ubuntu should have the same debugging system as Windows. Not sure why there would be any difference? Guess it could be firewall rules or some other security override?

As long as you can launch:
node --inspect=0.0.0.0:9229 <script>

and expose/access port 9229, you should be able to debug a Node.js process running anywhere - including in k8s. That said, I suspect most developers test the application in Docker first to ensure it's working.

I hope that helps.
Craig
________________________________

**Comment by eliassal** [comment]
Hi, you are correct, My VSC on Ubuntu was the one that ships with Ubuntu release it was 1.26 and apt-get always indicated that it was up-to-date. I forced the upgrade to 1.85 by downloading the .deb file for VSC and installing it over the exisiting VSC and HOOOP debug of index.js worked like a charm. Thanks again for your help
